# Generated by Django 6.0.1 on 2026-01-31 22:11

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("HUMAN", "Human"),
                            ("AGENT", "AI Agent"),
                            ("HYBRID", "Hybrid"),
                        ],
                        default="HUMAN",
                        max_length=10,
                    ),
                ),
                (
                    "wallet_address",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "privy_user_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("professional_title", models.CharField(max_length=200)),
                ("bio", models.TextField(blank=True, max_length=2000)),
                ("profile_picture", models.URLField(blank=True, null=True)),
                (
                    "creative_style",
                    models.CharField(default="professional", max_length=50),
                ),
                (
                    "preferred_industry",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("agent_capabilities", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reputation_score",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "credit_balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "agent_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_agents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "swappable": "AUTH_USER_MODEL",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="CreativeMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("MUSIC", "Music/Audio"),
                            ("VIDEO", "Video Content"),
                            ("DESIGN", "Design Portfolio"),
                            ("PHOTOGRAPHY", "Photography"),
                            ("WRITING", "Writing Samples"),
                            ("CODE", "Code Projects"),
                            ("ART", "Art & Illustration"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("file_url", models.URLField()),
                ("thumbnail_url", models.URLField(blank=True, null=True)),
                ("duration", models.IntegerField(blank=True, null=True)),
                ("file_size", models.IntegerField(blank=True, null=True)),
                ("creative_tags", models.JSONField(blank=True, default=list)),
                (
                    "artistic_style",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "professional_context",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "blockchain_hash",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "ownership_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("plays_count", models.IntegerField(default=0)),
                ("downloads_count", models.IntegerField(default=0)),
                ("shares_count", models.IntegerField(default=0)),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("verification_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creative_media",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProfessionalApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField()),
                (
                    "app_type",
                    models.CharField(
                        choices=[
                            ("TOOL", "Professional Tool"),
                            ("TEMPLATE", "Creative Template"),
                            ("WIDGET", "Profile Widget"),
                            ("ANALYTICS", "Analytics Dashboard"),
                            ("COLLABORATION", "Collaboration Tool"),
                            ("CREATIVE", "Creative Tool"),
                        ],
                        max_length=20,
                    ),
                ),
                ("certification_level", models.CharField(max_length=20)),
                ("user_rating", models.DecimalField(decimal_places=2, max_digits=3)),
                ("usage_count", models.IntegerField(default=0)),
                ("price_usd", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "revenue_share_percentage",
                    models.DecimalField(decimal_places=2, default=80.0, max_digits=5),
                ),
                (
                    "smart_contract_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "token_royalty_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("icon_url", models.URLField(blank=True, null=True)),
                ("screenshots", models.JSONField(blank=True, default=list)),
                ("api_documentation", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "developer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="developed_apps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProfessionalTheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                ("color_scheme", models.JSONField(blank=True, default=dict)),
                (
                    "layout_template",
                    models.CharField(default="professional", max_length=50),
                ),
                ("background_options", models.JSONField(blank=True, default=list)),
                ("font_preferences", models.JSONField(blank=True, default=dict)),
                (
                    "professional_rating",
                    models.DecimalField(decimal_places=2, max_digits=3),
                ),
                ("approved_for_business", models.BooleanField(default=False)),
                ("featured_theme", models.BooleanField(default=False)),
                ("usage_count", models.IntegerField(default=0)),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_for",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="themes_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_themes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TopConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.IntegerField(default=1)),
                ("collaboration_history", models.JSONField(blank=True, default=list)),
                ("business_context", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="featured_in_top8",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theme_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner_top_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "unique_together": {("user", "connection")},
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skills", models.JSONField(blank=True, default=list)),
                ("experience", models.JSONField(blank=True, default=list)),
                ("education", models.JSONField(blank=True, default=list)),
                ("certifications", models.JSONField(blank=True, default=list)),
                (
                    "theme_choice",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("custom_colors", models.JSONField(blank=True, default=dict)),
                (
                    "layout_preference",
                    models.CharField(default="professional", max_length=20),
                ),
                ("background_image", models.URLField(blank=True, null=True)),
                ("portfolio_media", models.JSONField(blank=True, default=list)),
                ("featured_audio", models.URLField(blank=True, null=True)),
                ("background_music", models.URLField(blank=True, null=True)),
                ("privacy_settings", models.JSONField(blank=True, default=dict)),
                ("notification_settings", models.JSONField(blank=True, default=dict)),
                (
                    "total_earned",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "total_spent",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "top_connections",
                    models.ManyToManyField(
                        blank=True,
                        related_name="featured_in_top8",
                        through="identity.TopConnection",
                        to="identity.userprofile",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
