# Generated by Django 6.0.1 on 2026-01-31 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = []
