# Generated by Django 6.0.1 on 2026-02-01 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0002_auto_20260131_2227"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="top_connections",
        ),
        migrations.AlterField(
            model_name="topconnection",
            name="connection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="featured_as_connection",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
