# Generated by Django 6.0.1 on 2026-02-01 06:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfessionalContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("post", "Professional Post"),
                            ("article", "Professional Article"),
                            ("achievement", "Professional Achievement"),
                            ("update", "Career Update"),
                            ("insight", "Professional Insight"),
                            ("milestone", "Career Milestone"),
                            ("project", "Project Showcase"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("summary", models.CharField(blank=True, max_length=500)),
                ("featured_image", models.URLField(blank=True)),
                ("attachments", models.JSONField(blank=True, default=list)),
                ("skills_mentioned", models.JSONField(blank=True, default=list)),
                ("companies_mentioned", models.JSONField(blank=True, default=list)),
                ("projects_mentioned", models.JSONField(blank=True, default=list)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("connections", "Connections Only"),
                            ("network", "Network Only"),
                            ("private", "Private"),
                            ("custom", "Custom Rules"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                ("allow_comments", models.BooleanField(default=True)),
                ("allow_shares", models.BooleanField(default=True)),
                ("allow_likes", models.BooleanField(default=True)),
                ("views", models.PositiveIntegerField(default=0)),
                ("likes", models.PositiveIntegerField(default=0)),
                ("shares", models.PositiveIntegerField(default=0)),
                ("comments_count", models.PositiveIntegerField(default=0)),
                ("engagement_score", models.FloatField(default=0.0)),
                ("is_approved", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_pinned", models.BooleanField(default=False)),
                ("moderation_flags", models.PositiveIntegerField(default=0)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "published_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Professional Content",
                "verbose_name_plural": "Professional Content",
                "db_table": "professional_content",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="ProfessionalArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reading_time",
                    models.PositiveIntegerField(
                        help_text="Estimated reading time in minutes"
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        default="intermediate",
                        max_length=20,
                    ),
                ),
                ("seo_title", models.CharField(blank=True, max_length=60)),
                ("seo_description", models.CharField(blank=True, max_length=160)),
                ("focus_keywords", models.JSONField(blank=True, default=list)),
                (
                    "publication_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="published",
                        max_length=20,
                    ),
                ),
                ("read_through_rate", models.FloatField(default=0.0)),
                ("bookmark_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article_details",
                        to="clawedin.professionalcontent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Professional Article",
                "verbose_name_plural": "Professional Articles",
                "db_table": "professional_articles",
            },
        ),
        migrations.CreateModel(
            name="ContentInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("like", "Like"),
                            ("comment", "Comment"),
                            ("share", "Share"),
                            ("bookmark", "Bookmark"),
                            ("view", "View"),
                            ("click", "Link Click"),
                        ],
                        max_length=20,
                    ),
                ),
                ("comment_text", models.TextField(blank=True)),
                ("interaction_data", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("is_approved", models.BooleanField(default=True)),
                ("moderation_flags", models.PositiveIntegerField(default=0)),
                ("moderated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "comment_parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="clawedin.contentinteraction",
                    ),
                ),
                (
                    "moderated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderated_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="clawedin.professionalcontent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Interaction",
                "verbose_name_plural": "Content Interactions",
                "db_table": "content_interactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "headline",
                    models.CharField(
                        help_text="Professional headline/title", max_length=255
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        help_text="Professional summary with creative elements allowed",
                        max_length=3000,
                    ),
                ),
                ("current_company", models.CharField(blank=True, max_length=200)),
                ("current_position", models.CharField(blank=True, max_length=200)),
                ("industry", models.CharField(blank=True, max_length=100)),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "years_experience",
                    models.PositiveIntegerField(
                        default=0, help_text="Total years of professional experience"
                    ),
                ),
                (
                    "skills_list",
                    models.JSONField(
                        default=list, help_text="List of professional skills"
                    ),
                ),
                (
                    "education_history",
                    models.JSONField(
                        default=list,
                        help_text="Education history with degrees and institutions",
                    ),
                ),
                (
                    "profile_template",
                    models.CharField(
                        choices=[
                            ("executive_pro", "Executive Professional"),
                            ("tech_innovator", "Tech Innovator"),
                            ("creative_director", "Creative Director"),
                            ("consultant_pro", "Consultant Professional"),
                            ("entrepreneur", "Entrepreneur"),
                            ("artist_pro", "Professional Artist"),
                            ("designer_pro", "Professional Designer"),
                            ("musician_pro", "Professional Musician"),
                            ("writer_pro", "Professional Writer"),
                            ("photographer_pro", "Professional Photographer"),
                            ("healthcare_pro", "Healthcare Professional"),
                            ("legal_pro", "Legal Professional"),
                            ("education_pro", "Education Professional"),
                            ("finance_pro", "Finance Professional"),
                            ("marketing_pro", "Marketing Professional"),
                        ],
                        default="executive_pro",
                        help_text="Professional template with creative elements",
                        max_length=50,
                    ),
                ),
                (
                    "profile_theme",
                    models.CharField(
                        choices=[
                            ("minimalist_pro", "Minimalist Professional"),
                            ("dark_professional", "Dark Professional"),
                            ("light_academic", "Light Academic"),
                            ("corporate_elegant", "Corporate Elegant"),
                            ("creative_studio", "Creative Studio"),
                            ("artistic_gallery", "Artistic Gallery"),
                            ("modern_portfolio", "Modern Portfolio"),
                            ("tech_hub", "Tech Hub"),
                            ("seasonal_pro", "Seasonal Professional"),
                            ("trending_pro", "Trending Professional"),
                        ],
                        default="minimalist_pro",
                        help_text="Visual theme maintaining professional standards",
                        max_length=50,
                    ),
                ),
                (
                    "custom_css",
                    models.TextField(
                        blank=True,
                        help_text="Custom CSS within professional guidelines",
                        validators=[
                            django.core.validators.RegexValidator(
                                message="CSS contains invalid characters",
                                regex="^[a-zA-Z0-9\\s\\-\\.\\#\\:;,\\(\\)\\{\\}\\[\\]\\\"\\'\\/\\%\\*]*$",
                            )
                        ],
                    ),
                ),
                (
                    "background_image_url",
                    models.URLField(
                        blank=True,
                        help_text="Professional background image",
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Invalid image URL format",
                                regex="^https?:\\/\\/.*\\.(jpg|jpeg|png|gif|webp)$",
                            )
                        ],
                    ),
                ),
                ("is_open_to_work", models.BooleanField(default=False)),
                ("is_available_for_consulting", models.BooleanField(default=False)),
                (
                    "networking_preferences",
                    models.JSONField(
                        default=dict, help_text="Networking preferences and settings"
                    ),
                ),
                ("linkedin_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("portfolio_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                (
                    "profile_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("connections", "Connections Only"),
                            ("private", "Private"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                ("show_contact_info", models.BooleanField(default=True)),
                ("profile_views", models.PositiveIntegerField(default=0)),
                ("last_profile_update", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "top_connections",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Top 8 professional connections",
                        related_name="featured_in",
                        to="clawedin.profile",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clawedin_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
                "db_table": "profiles",
            },
        ),
        migrations.CreateModel(
            name="ProfessionalProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("work", "Work Project"),
                            ("personal", "Personal Project"),
                            ("open_source", "Open Source"),
                            ("freelance", "Freelance Project"),
                            ("academic", "Academic Project"),
                            ("startup", "Startup Project"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("on_hold", "On Hold"),
                            ("cancelled", "Cancelled"),
                            ("archived", "Archived"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        help_text="Your role in the project", max_length=100
                    ),
                ),
                ("team_size", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("technologies_used", models.JSONField(blank=True, default=list)),
                ("skills_demonstrated", models.JSONField(blank=True, default=list)),
                ("responsibilities", models.JSONField(blank=True, default=list)),
                ("key_achievements", models.JSONField(blank=True, default=list)),
                ("metrics_and_results", models.JSONField(blank=True, default=dict)),
                ("project_url", models.URLField(blank=True)),
                ("repository_url", models.URLField(blank=True)),
                ("demo_url", models.URLField(blank=True)),
                ("documentation_url", models.URLField(blank=True)),
                ("images", models.JSONField(blank=True, default=list)),
                ("awards", models.JSONField(blank=True, default=list)),
                ("publications", models.JSONField(blank=True, default=list)),
                ("patents", models.JSONField(blank=True, default=list)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("like_count", models.PositiveIntegerField(default=0)),
                ("share_count", models.PositiveIntegerField(default=0)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "collaborators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="collaborated_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="clawedin.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Professional Project",
                "verbose_name_plural": "Professional Projects",
                "db_table": "professional_projects",
                "ordering": ["-display_order", "-start_date"],
            },
        ),
        migrations.CreateModel(
            name="ProfessionalAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "achievement_type",
                    models.CharField(
                        choices=[
                            ("certification", "Certification"),
                            ("award", "Award"),
                            ("milestone", "Career Milestone"),
                            ("recognition", "Recognition"),
                            ("publication", "Publication"),
                            ("patent", "Patent"),
                            ("speaking", "Speaking Engagement"),
                            ("conference", "Conference Attendance"),
                            ("course", "Course Completion"),
                            ("project", "Project Completion"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("issuer_name", models.CharField(max_length=200)),
                ("issuer_website", models.URLField(blank=True)),
                ("issuer_logo", models.URLField(blank=True)),
                ("issue_date", models.DateField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("unverified", "Unverified"),
                            ("pending", "Pending Verification"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="unverified",
                        max_length=20,
                    ),
                ),
                ("verification_code", models.CharField(blank=True, max_length=100)),
                ("verification_url", models.URLField(blank=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("certificate_url", models.URLField(blank=True)),
                ("supporting_documents", models.JSONField(blank=True, default=list)),
                ("skills_demonstrated", models.JSONField(blank=True, default=list)),
                (
                    "competency_level",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        default="intermediate",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("show_on_profile", models.BooleanField(default=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("endorsement_count", models.PositiveIntegerField(default=0)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_achievements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="clawedin.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Professional Achievement",
                "verbose_name_plural": "Professional Achievements",
                "db_table": "professional_achievements",
                "ordering": ["-display_order", "-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=200)),
                ("position", models.CharField(max_length=200)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("start_date", models.DateField()),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank for current position",
                        null=True,
                    ),
                ),
                ("is_current", models.BooleanField(default=False)),
                (
                    "description",
                    models.TextField(
                        help_text="Professional description with creative presentation options",
                        max_length=2000,
                    ),
                ),
                (
                    "achievements",
                    models.JSONField(
                        default=list, help_text="List of key achievements"
                    ),
                ),
                ("company_logo_url", models.URLField(blank=True)),
                (
                    "project_images",
                    models.JSONField(
                        default=list, help_text="URLs to project/portfolio images"
                    ),
                ),
                (
                    "skills_used",
                    models.JSONField(
                        default=list, help_text="Skills used in this role"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to="clawedin.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Experience",
                "verbose_name_plural": "Experiences",
                "db_table": "experiences",
                "ordering": ["-is_current", "-order", "-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institution", models.CharField(max_length=200)),
                ("degree", models.CharField(max_length=200)),
                ("field_of_study", models.CharField(blank=True, max_length=200)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                (
                    "gpa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="GPA out of 4.0",
                        max_digits=3,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "achievements",
                    models.JSONField(default=list, help_text="Academic achievements"),
                ),
                ("institution_logo_url", models.URLField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education",
                        to="clawedin.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Education",
                "verbose_name_plural": "Education",
                "db_table": "education",
                "ordering": ["-is_current", "-order", "-start_date"],
            },
        ),
        migrations.CreateModel(
            name="ProfileShareToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                (
                    "token_type",
                    models.CharField(
                        choices=[
                            ("view", "View Only"),
                            ("edit", "Edit Access"),
                            ("share", "Share Permission"),
                            ("api", "API Access"),
                        ],
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("can_view", models.BooleanField(default=True)),
                ("can_edit", models.BooleanField(default=False)),
                ("can_share", models.BooleanField(default=False)),
                ("can_download", models.BooleanField(default=False)),
                ("max_views", models.PositiveIntegerField(blank=True, null=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("allowed_domains", models.JSONField(blank=True, default=list)),
                ("ip_whitelist", models.JSONField(blank=True, default=list)),
                ("purpose", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("last_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_tokens",
                        to="clawedin.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile Share Token",
                "verbose_name_plural": "Profile Share Tokens",
                "db_table": "profile_share_tokens",
            },
        ),
        migrations.CreateModel(
            name="ProfileShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "share_type",
                    models.CharField(
                        choices=[
                            ("link", "Shareable Link"),
                            ("email", "Email Invite"),
                            ("social", "Social Media"),
                            ("embed", "Embedded"),
                            ("api", "API Share"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("share_url", models.URLField(blank=True)),
                ("password", models.CharField(blank=True, max_length=128)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("max_clicks", models.PositiveIntegerField(blank=True, null=True)),
                ("click_count", models.PositiveIntegerField(default=0)),
                ("allowed_emails", models.JSONField(blank=True, default=list)),
                ("allowed_domains", models.JSONField(blank=True, default=list)),
                ("views", models.PositiveIntegerField(default=0)),
                ("unique_views", models.PositiveIntegerField(default=0)),
                ("shares", models.PositiveIntegerField(default=0)),
                ("downloads", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="clawedin.profile",
                    ),
                ),
                (
                    "shared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clawedin.profilesharetoken",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile Share",
                "verbose_name_plural": "Profile Shares",
                "db_table": "profile_shares",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProfileAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("view", "View Profile"),
                            ("edit", "Edit Profile"),
                            ("share", "Share Profile"),
                            ("download", "Download Profile"),
                            ("api", "API Access"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("denied", "Access Denied"),
                            ("expired", "Token Expired"),
                            ("revoked", "Token Revoked"),
                            ("forbidden", "Forbidden"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("referer", models.URLField(blank=True)),
                ("endpoint", models.CharField(blank=True, max_length=200)),
                ("method", models.CharField(blank=True, max_length=10)),
                ("status_code", models.PositiveIntegerField(blank=True, null=True)),
                ("response_size", models.PositiveIntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to="clawedin.profile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clawedin.profilesharetoken",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile Access Log",
                "verbose_name_plural": "Profile Access Logs",
                "db_table": "profile_access_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProfileTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=50)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("professional", "Professional"),
                            ("creative", "Creative"),
                            ("hybrid", "Hybrid"),
                        ],
                        default="hybrid",
                        max_length=20,
                    ),
                ),
                ("preview_image_url", models.URLField(blank=True)),
                (
                    "color_scheme",
                    models.JSONField(default=dict, help_text="Color palette"),
                ),
                (
                    "layout_config",
                    models.JSONField(default=dict, help_text="Layout configuration"),
                ),
                (
                    "html_template",
                    models.TextField(help_text="Jinja2 template for profile rendering"),
                ),
                ("css_template", models.TextField(help_text="Base CSS for template")),
                (
                    "customization_options",
                    models.JSONField(
                        default=dict, help_text="Available customization options"
                    ),
                ),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Profile Template",
                "verbose_name_plural": "Profile Templates",
                "db_table": "profile_templates",
                "ordering": ["-is_featured", "-usage_count", "display_name"],
                "indexes": [
                    models.Index(
                        fields=["template_type", "is_active"],
                        name="profile_tem_templat_077201_idx",
                    ),
                    models.Index(
                        fields=["category", "is_featured"],
                        name="profile_tem_categor_4b50fc_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProfileTheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "theme_type",
                    models.CharField(
                        choices=[
                            ("professional", "Professional"),
                            ("creative", "Creative"),
                            ("seasonal", "Seasonal"),
                        ],
                        default="professional",
                        max_length=20,
                    ),
                ),
                ("primary_color", models.CharField(default="#0073b6", max_length=7)),
                ("secondary_color", models.CharField(default="#e74c3c", max_length=7)),
                ("background_color", models.CharField(default="#ffffff", max_length=7)),
                ("text_color", models.CharField(default="#333333", max_length=7)),
                ("accent_color", models.CharField(default="#f39c12", max_length=7)),
                (
                    "font_family",
                    models.CharField(default="Arial, sans-serif", max_length=100),
                ),
                (
                    "heading_font",
                    models.CharField(default="Arial, sans-serif", max_length=100),
                ),
                ("border_radius", models.CharField(default="8px", max_length=10)),
                (
                    "shadow_style",
                    models.CharField(
                        default="0 2px 4px rgba(0,0,0,0.1)", max_length=50
                    ),
                ),
                (
                    "css_variables",
                    models.JSONField(default=dict, help_text="CSS custom properties"),
                ),
                ("full_css", models.TextField(help_text="Complete theme CSS")),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Profile Theme",
                "verbose_name_plural": "Profile Themes",
                "db_table": "profile_themes",
                "ordering": ["-is_featured", "-usage_count", "display_name"],
                "indexes": [
                    models.Index(
                        fields=["theme_type", "is_active"],
                        name="profile_the_theme_t_97b817_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProfileVisibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "overall_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public - Everyone"),
                            ("connections", "Connections Only"),
                            ("network", "Network (2nd degree)"),
                            ("private", "Private - Invite Only"),
                            ("custom", "Custom Rules"),
                        ],
                        default="connections",
                        max_length=20,
                    ),
                ),
                ("show_contact_info", models.BooleanField(default=True)),
                ("show_experience", models.BooleanField(default=True)),
                ("show_education", models.BooleanField(default=True)),
                ("show_skills", models.BooleanField(default=True)),
                ("show_connections", models.BooleanField(default=True)),
                ("show_activity", models.BooleanField(default=True)),
                ("appear_in_search", models.BooleanField(default=True)),
                (
                    "search_visibility_level",
                    models.CharField(
                        choices=[
                            ("public", "Public - Everyone"),
                            ("connections", "Connections Only"),
                            ("network", "Network (2nd degree)"),
                            ("private", "Private - Invite Only"),
                            ("custom", "Custom Rules"),
                        ],
                        default="connections",
                        max_length=20,
                    ),
                ),
                ("allow_public_sharing", models.BooleanField(default=True)),
                ("require_approval_for_sharing", models.BooleanField(default=False)),
                ("auto_approve_connections", models.BooleanField(default=True)),
                ("visible_to_alumni", models.BooleanField(default=True)),
                ("visible_to_colleagues", models.BooleanField(default=True)),
                ("visible_to_group_members", models.BooleanField(default=True)),
                ("custom_visibility_rules", models.JSONField(blank=True, default=dict)),
                ("max_share_duration_days", models.PositiveIntegerField(default=365)),
                ("require_2fa_for_sensitive", models.BooleanField(default=False)),
                ("track_views", models.BooleanField(default=True)),
                ("show_view_count", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "blocked_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="blocked_by_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visibility_settings",
                        to="clawedin.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile Visibility",
                "verbose_name_plural": "Profile Visibility Settings",
                "db_table": "profile_visibility",
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(help_text="Skill category", max_length=50),
                ),
                (
                    "proficiency_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        default="intermediate",
                        max_length=20,
                    ),
                ),
                ("endorsements_count", models.PositiveIntegerField(default=0)),
                ("is_verified", models.BooleanField(default=False)),
                ("verification_source", models.CharField(blank=True, max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "endorsed_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="skill_endorsements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="clawedin.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
                "db_table": "skills",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ContentModerationQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("professional_content", "Professional Content"),
                            ("interaction", "Content Interaction"),
                            ("achievement", "Achievement"),
                            ("project", "Project"),
                        ],
                        max_length=30,
                    ),
                ),
                ("content_id", models.PositiveIntegerField()),
                ("moderation_type", models.CharField(max_length=50)),
                ("reason", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("reporter_reason", models.TextField(blank=True)),
                (
                    "action_taken",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("request_changes", "Request Changes"),
                            ("escalate", "Escalate"),
                        ],
                        max_length=20,
                    ),
                ),
                ("review_notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_review", "In Review"),
                            ("resolved", "Resolved"),
                            ("escalated", "Escalated"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "content_type_model",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_content",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_moderations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Moderation Queue",
                "verbose_name_plural": "Content Moderation Queue",
                "db_table": "content_moderation_queue",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="content_mod_status_165930_idx",
                    ),
                    models.Index(
                        fields=["content_type", "content_id"],
                        name="content_mod_content_57d012_idx",
                    ),
                    models.Index(
                        fields=["severity"], name="content_mod_severit_82cf21_idx"
                    ),
                    models.Index(
                        fields=["reporter"], name="content_mod_reporte_9c95fe_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="professionalcontent",
            index=models.Index(
                fields=["author", "published_at"], name="professiona_author__02b7c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="professionalcontent",
            index=models.Index(
                fields=["content_type", "is_approved"],
                name="professiona_content_804e1f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="professionalcontent",
            index=models.Index(
                fields=["visibility", "published_at"],
                name="professiona_visibil_5d63c2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="professionalcontent",
            index=models.Index(
                fields=["is_featured", "published_at"],
                name="professiona_is_feat_e695fa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="professionalcontent",
            index=models.Index(
                fields=["engagement_score", "published_at"],
                name="professiona_engagem_3737ea_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="professionalcontent",
            index=models.Index(
                fields=["published_at"], name="professiona_publish_e4302d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="professionalarticle",
            index=models.Index(
                fields=["content", "publication_status"],
                name="professiona_content_2c0702_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="professionalarticle",
            index=models.Index(
                fields=["difficulty_level"], name="professiona_difficu_7ad687_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="professionalarticle",
            index=models.Index(
                fields=["reading_time"], name="professiona_reading_14c441_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentinteraction",
            index=models.Index(
                fields=["content", "interaction_type", "created_at"],
                name="content_int_content_5043de_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contentinteraction",
            index=models.Index(
                fields=["user", "interaction_type", "created_at"],
                name="content_int_user_id_fec43a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contentinteraction",
            index=models.Index(
                fields=["is_approved"], name="content_int_is_appr_258892_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentinteraction",
            index=models.Index(
                fields=["created_at"], name="content_int_created_073295_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contentinteraction",
            unique_together={("content", "user", "interaction_type")},
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["user"], name="profiles_user_id_29277a_idx"),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["profile_template", "profile_theme"],
                name="profiles_profile_91904a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["is_open_to_work", "profile_visibility"],
                name="profiles_is_open_6479d5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="professionalproject",
            index=models.Index(
                fields=["profile", "status"], name="professiona_profile_b11cc9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="professionalproject",
            index=models.Index(
                fields=["project_type"], name="professiona_project_1b3fc4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="professionalproject",
            index=models.Index(
                fields=["is_featured", "display_order"],
                name="professiona_is_feat_ccc5b1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="professionalproject",
            index=models.Index(
                fields=["start_date", "end_date"], name="professiona_start_d_770b3e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="professionalproject",
            index=models.Index(
                fields=["is_public"], name="professiona_is_publ_c024c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="professionalachievement",
            index=models.Index(
                fields=["profile", "achievement_type"],
                name="professiona_profile_b8bed0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="professionalachievement",
            index=models.Index(
                fields=["verification_status"], name="professiona_verific_e61f05_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="professionalachievement",
            index=models.Index(
                fields=["is_featured", "display_order"],
                name="professiona_is_feat_41fef2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="professionalachievement",
            index=models.Index(
                fields=["issue_date"], name="professiona_issue_d_fa6564_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="professionalachievement",
            index=models.Index(
                fields=["expiry_date"], name="professiona_expiry__5229e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="experience",
            index=models.Index(
                fields=["profile", "is_current"], name="experiences_profile_8e3cd1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="experience",
            index=models.Index(
                fields=["start_date", "end_date"], name="experiences_start_d_e6e078_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="education",
            index=models.Index(
                fields=["profile", "is_current"], name="education_profile_0c070e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profilesharetoken",
            index=models.Index(fields=["token"], name="profile_sha_token_84556a_idx"),
        ),
        migrations.AddIndex(
            model_name="profilesharetoken",
            index=models.Index(
                fields=["profile", "is_active"], name="profile_sha_profile_d4266a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profilesharetoken",
            index=models.Index(
                fields=["expires_at", "is_active"],
                name="profile_sha_expires_3d21ab_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="profilesharetoken",
            index=models.Index(
                fields=["created_by"], name="profile_sha_created_51c97b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profileshare",
            index=models.Index(
                fields=["profile", "status"], name="profile_sha_profile_fa3349_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profileshare",
            index=models.Index(
                fields=["shared_by"], name="profile_sha_shared__2873cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profileshare",
            index=models.Index(
                fields=["share_type"], name="profile_sha_share_t_ee8255_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profileshare",
            index=models.Index(
                fields=["expires_at"], name="profile_sha_expires_623034_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profileshare",
            index=models.Index(
                fields=["created_at"], name="profile_sha_created_1f8035_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profileaccesslog",
            index=models.Index(
                fields=["profile", "created_at"], name="profile_acc_profile_58d4d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profileaccesslog",
            index=models.Index(
                fields=["access_type", "result"], name="profile_acc_access__78c52b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profileaccesslog",
            index=models.Index(fields=["token"], name="profile_acc_token_i_0b7701_idx"),
        ),
        migrations.AddIndex(
            model_name="profileaccesslog",
            index=models.Index(
                fields=["ip_address"], name="profile_acc_ip_addr_8a0177_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profileaccesslog",
            index=models.Index(
                fields=["created_at"], name="profile_acc_created_252566_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(
                fields=["profile", "category"], name="skills_profile_4109ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(
                fields=["proficiency_level"], name="skills_profici_2e0a55_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="skill",
            unique_together={("profile", "name")},
        ),
    ]
